# Generated by Django 4.1.2 on 2022-11-17 20:46

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Add ingredient to your recipe', max_length=250, verbose_name='Ingredient')),
                ('measurement_unit', models.CharField(help_text='Add units for this ingredient', max_length=50, verbose_name='Units')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Recipe name', max_length=50, unique=True, verbose_name='Recipe name')),
                ('image', models.ImageField(blank=True, help_text='Upload your image', upload_to='recipes/', verbose_name='Image')),
                ('text', models.TextField(help_text='Type your recipe', verbose_name='Text')),
                ('cooking_time', models.IntegerField(help_text='Enter cooking time for your recipe', verbose_name='Cooking time')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Publication date')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=0, help_text='Add how much of ingredient you need for your recipe', verbose_name='Ingredient amount')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Choose tag for your recipe', max_length=50, unique=True, verbose_name='Tag')),
                ('color', models.CharField(default='#0000ff', help_text='Choose color HEX-code ', max_length=7, unique=True, validators=[api.validators.hex_code_validator], verbose_name='Color code')),
                ('slug', models.SlugField(help_text='Type unique tag slug', max_length=20, unique=True, verbose_name='Tag slug')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
