# Generated by Django 2.2.16 on 2022-10-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingridient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Add ingridient to your recipe', max_length=50, unique=True, verbose_name='Ingridient')),
                ('amount', models.FloatField(help_text='Add how much of ingridient you need for your recipe', verbose_name='Ingridient amount')),
                ('units', models.CharField(help_text='Add units for this ingridient', max_length=5, verbose_name='Units')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Choose tag for your recipe', max_length=50, unique=True, verbose_name='Tag')),
                ('color', models.CharField(help_text='Choose color HEX-code ', max_length=50, unique=True, verbose_name='Color code')),
                ('slug', models.SlugField(help_text='Type unique tag slug', max_length=20, unique=True, verbose_name='Tag slug')),
            ],
        ),
    ]
