# Generated by Django 2.2.16 on 2022-10-21 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Recipe title', max_length=50, verbose_name='Title')),
                ('image', models.ImageField(blank=True, help_text='Upload your image', upload_to='recipes/images', verbose_name='Image')),
                ('text', models.TextField(help_text='Type your recipe', verbose_name='Text')),
                ('cooking_time', models.IntegerField(help_text='Enter cooking time fot your recipe', verbose_name='Cooking time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to=settings.AUTH_USER_MODEL, verbose_name='Recipe')),
            ],
        ),
    ]
