# Generated by Django 2.2.16 on 2022-10-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Add ingredient to your recipe', max_length=50, unique=True, verbose_name='Ingredient')),
                ('amount', models.FloatField(help_text='Add how much of ingredient you need for your recipe', verbose_name='Ingredient amount')),
                ('units', models.CharField(help_text='Add units for this ingredient', max_length=5, verbose_name='Units')),
            ],
        ),
        migrations.DeleteModel(
            name='Ingridient',
        ),
    ]
