# Generated by Django 4.1.2 on 2022-11-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload your image', upload_to='recipes/images', verbose_name='Image'),
        ),
    ]
