# Generated by Django 2.2.16 on 2022-10-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20221021_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredients',
            name='amount',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.FloatField(default=0, help_text='Add how much of ingredient you need for your recipe', verbose_name='Ingredient amount'),
        ),
    ]
