# Generated by Django 4.1.2 on 2022-11-19 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='recipe',
            new_name='in_recipe',
        ),
    ]
