# Generated by Django 4.1.2 on 2022-11-19 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_recipe_recipeingredients_in_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredients',
            name='in_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='recipes.recipe', verbose_name='Recipe'),
        ),
    ]
