# Generated by Django 2.2.16 on 2022-10-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
        migrations.AddField(
            model_name='recipeingredients',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0, help_text='Add how much of ingredient you need for your recipe', verbose_name='Ingredient amount'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(help_text='Enter cooking time for your recipe', verbose_name='Cooking time'),
        ),
    ]
