# Generated by Django 4.1.2 on 2022-11-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipeingredients_in_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='recipes.recipeingredients', verbose_name='Ingredients'),
        ),
    ]
