# Generated by Django 4.1.2 on 2022-11-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='in_recipe',
            new_name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.RecipeIngredients', to='recipes.ingredient', verbose_name='Ingredients'),
        ),
    ]
