# Generated by Django 4.1.2 on 2022-11-19 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_rename_in_recipe_recipeingredients_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredients',
            name='amount',
            field=models.PositiveSmallIntegerField(help_text='Add how much of ingredient you need for your recipe', validators=[django.core.validators.MinValueValidator(1, message='Amount of ingredient should be more than 0!')], verbose_name='Ingredient amount'),
        ),
    ]
