# Generated by Django 2.2.16 on 2022-10-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20221024_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(help_text='Add units for this ingredient', max_length=50, verbose_name='Units'),
        ),
    ]
