# Generated by Django 2.2.16 on 2022-10-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20221024_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Add ingredient to your recipe', max_length=250, unique=True, verbose_name='Ingredient'),
        ),
    ]
