# Generated by Django 4.1.2 on 2022-11-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Upload your image', upload_to='recipes/images', verbose_name='Image'),
        ),
    ]
