# Generated by Django 4.1.2 on 2022-11-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_remove_subscription_self-subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(help_text='Recipe name', max_length=50, verbose_name='Recipe name'),
        ),
    ]
